### PR TITLE
Prettier tcltk code and zero out buffer using tcltk's native object

### PR DESCRIPTION
**Pull request by snoweye**
- Add focus back to main textbox when the message box is closed.
- Add title to main frame and message box.
- Get rid of tryCatch().

### CODE REVIEW

**Comment by snoweye** [comment]
Add zero out buffer

**Comment by wrathematics** [comment]
That doesn't zero the buffer. I'm not convinced it isn't operating by copying, but even if it's not, it's just changing `"super secret password\0"` to `"\0uper secret password\0"`

**Comment by snoweye** [comment]
No, it does not. There are actually too many copies that I can not erase them all. Even I can get the pointer address from `tclvar()`, this is the only one I can erase. I don't have a better way right now, and I doubt I can get the pointer without hijacking the `tcltk` package.

**Comment by snoweye** [comment]
- Luckily, there is an opposite way to do hijacking. :-D I am sure this is good enough.
- R CMD checked.
- Solaris tested.
- Change permission.
- Modify travis.yml
- Get rid of suggests to reduce travis.yml building time. This is not working, so I roll them back. I suggest to get rid of those. Just pre-build them and put them at inst/ to avoid very long rebuilding process and long dependence of dependence.
- Add xbvfb to fake X window

**Comment by snoweye** [comment]
Solaris tested.

**Comment by wrathematics** [comment]
This is devilish!

Let me test it a bit in a few days. I still have to make my slides for my presentation on Tuesday 😳

**Comment by wrathematics** [comment]
I had to drop almost all of this because it breaks everything.

**Pull request merged**
